web_root_path: /srv/www
web_server_group: www-data

app_name: app
app_root_path: "{{ web_root_path }}/{{ app_name }}_webapp"

# NGINX
app_nginx_hostname: localhost
app_nginx_static_path: "{{ app_root_path }}/{{ app_name }}/static/"

# UWSGI
app_uwsgi_port: 8000
app_uwsgi_executable: "app:make_wsgi_app()"
app_uwsgi_envs: {}
